import '../../styles/global.css'
import '../../styles/variables.css'

import { jakarta, jakartaItalic, kahroba, nuestadt, yekanBakh } from '@/fonts/fonts'
import LoadingPage from './loading/page'
import MainLoader from '@/components/loaders/MainLoader'
import { CursorProvider } from '@/components/cursors/CursorContext'
import CustomCursor from '@/components/cursors/CustomCursor'
import Desktop from '@/components/layout/desktop/Desktop'

import { ToastContainer, Slide, Zoom, Flip, Bounce } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import CustomTransition from '@/components/layout/notificationBox/CustomTransition' // ایمپورت ترنزیشن سفارشی
import WindowControlButtons from '@/components/layout/windowControl/WindowControlButton'
import HeightControl from '@/components/layout/heightControl/HeightControl'
import Stats from '@/components/layout/stats/Stats'
import People from '@/components/layout/people/People'
import TaskBar from '@/components/layout/taskBar/TaskBar'
import AppOnDesktop from '@/components/appIcons/AppOnDesktop'
import DesktopBackground from '@/components/layout/desktop/DesktopBackground'
import styles from "./layout.module.css"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kahroba.variable} ${yekanBakh.variable} ${jakarta.variable} ${jakartaItalic.variable} ${nuestadt.variable} ${styles.background}`}
      >
        <CursorProvider>
          <CustomCursor canUse={true} />
          <DesktopBackground />
          <Desktop />
          {children}
          {/* کامپوننت Desktop باید در مسیر app/desktop/[desktopId]/page.js فراخوانی شود */}
          <ToastContainer
            position="bottom-left"
            autoClose={3000}
            hideProgressBar={true}
            progressStyle={{ display: 'none' }}
            newestOnTop={true}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            limit={3}
            // transition={CustomTransition}
            transition={Zoom}
            draggablePercent={80}
            className="toast"
            toastClassName="toast2"
            bodyClassName="toast3"
            progressClassName="toast4"
            closeButton={false}

            // stacked
          />
          {/* <LoadingPage /> */}
          <MainLoader />
        </CursorProvider>
      </body>
    </html>
  )
}
